site_name: Luis Henrique Miranda dos Santos - Fab Academy 2021

repo_name: 'riquemrd/FabAcademy'
repo_url: 'https://github.com/riquemrd/FabAcademy'
site_description: '2021 FabAcademy Project Documentation'
site_author: 'riquemrd'
site_url: 'https://riquemrd.github.io/FabAcademy/'
copyright: 'Creative Commons Attribution Non Commercial'


theme:
    name: material

    # 404 page
    static_templates:
        - 404.html

    # Necessary for search to work properly
    include_search_page: false
    search_index_only: true

    features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - toc.integrate
        - navigation.instant

    font:
        text: Roboto
        code: Roboto Mono

    palette:
    #light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: green 
          accent: green
          toggle:
            icon: material/weather-night  
            name: Switch to dark mode


    #dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue grey
          accent: green
          toggle:
            icon: material/weather-sunny 
            name: Switch to light mode



# extras
extra_css:
    - docs/css/extra.css

nav:
  - Home: index.md
  - About:
      - About me: about.md
      - Fab Academy Student Agreement: Agreement.md
  - Assignments:
      - 1. Principles and Practices: 
          - Individual Assignment: 1Ind.md
      - 2. Project Management: 
          - Individual Assignment: 2Ind.md
      - 3. Computer Aided Design:
          - Group Assignment: 3Group.md
#         - Individual Assignment: 3Ind.md
      - 4. Computer Controlled Cutting:
          - Group Assignment: 4Group.md
#         - Individual Assignment: 4Ind.md
      - 5. Electronics Production :
          - Group Assignment: 5Group.md
#         - Individual Assignment: 5Ind.md
#     - 6. 3D Scanning and Printing :
#         - Group Assignment: 6Group.md
#         - Individual Assignment: 6Ind.md
#     - 7. Electronics Design :
#         - Group Assignment: 7Group.md
#         - Individual Assignment: 7Ind.md
#     - 8. Computer Controlled Machining :
#         - Group Assignment: 8Group.md
#         - Individual Assignment: 8Ind.md
#     - 9. Embedded Programming :
#         - Group Assignment: 9Group.md
#         - Individual Assignment: 9Ind.md
#     - 10. Mechanical Design, Machine Design :
#         - Group Assignment: 10Group.md
#         - Individual Assignment: 10Ind.md
#     - 11. Input Devices :
#         - Group Assignment: 11Group.md
#         - Individual Assignment: 11Ind.md
#     - 12. Moulding and Casting :
#         - Group Assignment: 12Group.md
#         - Individual Assignment: 12Ind.md
#     - 13. Output Devices :
#         - Group Assignment: 13Group.md
#         - Individual Assignment: 13Ind.md
#     - 14. Embedded Networking and Communications :
#         - Group Assignment: 14Group.md
#         - Individual Assignment: 14Ind.md
#     - 15. Interface and Application Programming :
#         - Group Assignment: 15Group.md
#         - Individual Assignment: 15Ind.md
#     - 16. Wildcard Week :
#         - Group Assignment: 16Group.md
#         - Individual Assignment: 16Ind.md
#     - 17. Applications and Implications :
#         - Group Assignment: 17Group.md
#         - Individual Assignment: 17Ind.md
#     - 18. Invention, Intellectual Property and Business Models :
#         - Group Assignment: 18Group.md
#         - Individual Assignment: 18Ind.md
#     - 19. Project Development :
#         - Group Assignment: 19Group.md
#         - Individual Assignment: 19Ind.md


markdown_extensions:
    - attr_list
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.highlight
    - admonition #Admonitions are created by !!!type
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search
